title: Kevin's Triangle Pages
description: Kevin's Triangle Pages
theme: just-the-docs

url: https://kevnyc.github.io/triangle

aux_links:
  Main Triangle Page: http://www.triangle.org


kramdown:
  toc_levels: 2..3
