title: Kevin's Triangle Pages 25
description: Kevin's Triangle Pages 25
theme: just-the-docs

url: https://kevnyc.github.io/triangle25

aux_links:
  Main Triangle Page: http://www.triangle.org


kramdown:
  toc_levels: 2..3
