title: Kevin's Triangle Pages 2025
description: Kevin's Triangle Pages 2025
theme: just-the-docs

url: https://kevnyc.github.io/triangle2025

aux_links:
  Main Triangle Page: http://www.triangle.org


kramdown:
  toc_levels: 2..3
